addons:
  sonarcloud:
    organization: "sgt390-github"
    token:
      secure: "1d4a6c2e6682736c28eb9499fb8b3a06710eac3d"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  #- yes | sdkmanager "platforms;android-27"
   - cd MegAlexa
script:
   - ./gradlew build --status