addons:
  sonarcloud:
    organization: "sgt390-github"
    token:
      secure: "1d4a6c2e6682736c28eb9499fb8b3a06710eac3d"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
   - cd MegAlexa
   jobs:
  include:
    - stage: test
      name: "Static tests"
      script: sonar-scanner
    - name: "Unit tests"
      script: ./gradlew build
    - name: "Integration tests"
      script: skip
    - stage: deploy
      script: skip