addons:
  sonarcloud:
    organization: "sgt390-github"
    token:
      secure: "1d4a6c2e6682736c28eb9499fb8b3a06710eac3d"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
before_install:
  - yes | sdkmanager "platforms;android-27"
script:
   - cd MegAlexa
   - ./gradlew build